UPLOAD_FOLDER_NAME = "uploaded_files"
COMPLETE_MESSAGE = "Completed the task."

# 优先使用Gemini模型
DEFAULT_MODEL = "gemini-1.5-pro-latest"

TOKEN_BUDGET = 120_000
SUMMARY_MAX_TOKENS = 4000
VISIT_WEB_PAGE_MAX_OUTPUT_LENGTH = 40_000
